// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://sfxukwbckslyscjtirae.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNmeHVrd2Jja3NseXNjanRpcmFlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTcwNDc4NzEsImV4cCI6MjA3MjYyMzg3MX0.C39qjsTOWSTqFj4guQT37kMqq4m9UBGOGZbENDtp8xI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});